<?php

namespace Database\Seeders;

use App\Models\student;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StudentSeeder extends Seeder
{
    public function run()
    {
        $siswaList = [
            [
                'name' => 'Mellitya Silviandro Hening',
                'gender' => 'Perempuan',
                'birthplace_and_date' => 'Cimahi, 28/05/2020',
                'Umur_Tahun' => 50,
                'Afirmasi_Perpindahan_Orang_Tua' => 45,
                'Potensi_Kecerdasan' => 50,
                'Penghasilan_Orang_Tua_Rupiah' => 50,
                'Kemampuan_Komunikasi' => 50,
                'Ketaatan_Beragama' => 50,
                'Prestasi' => 30,
                'Kedisiplinan' => 50,
                'Kepedulian' => 50,
                'Jarak' => 50,
            ],

            [
                'name' => 'Angga Rifai Zul Fiqri',
                'gender' => 'laki-laki',
                'birthplace_and_date' => 'Jakarta, 13/09/2015',
                'Umur_Tahun' => 40,
                'Afirmasi_Perpindahan_Orang_Tua' => 50,
                'Potensi_Kecerdasan' => 30,
                'Penghasilan_Orang_Tua_Rupiah' => 10,
                'Kemampuan_Komunikasi' => 40,
                'Ketaatan_Beragama' => 30,
                'Prestasi' => 40,
                'Kedisiplinan' => 30,
                'Kepedulian' => 30,
                'Jarak' => 30,
            ],

            [
                'name' => 'Anggun Sintiara',
                'gender' => 'perempuan',
                'birthplace_and_date' => 'Surabaya, 05/11/2016',
                'Umur_Tahun' => 50,
                'Afirmasi_Perpindahan_Orang_Tua' => 50,
                'Potensi_Kecerdasan' => 40,
                'Penghasilan_Orang_Tua_Rupiah' => 10,
                'Kemampuan_Komunikasi' => 50,
                'Ketaatan_Beragama' => 20,
                'Prestasi' => 40,
                'Kedisiplinan' => 30,
                'Kepedulian' => 20,
                'Jarak' => 30,
            ],

            [
                'name' => 'Arisha Naimi Athirah',
                'gender' => 'perempuan',
                'birthplace_and_date' => 'Bandung, 22/07/2017',
                'Umur_Tahun' => 40,
                'Afirmasi_Perpindahan_Orang_Tua' => 50,
                'Potensi_Kecerdasan' => 50,
                'Penghasilan_Orang_Tua_Rupiah' => 50,
                'Kemampuan_Komunikasi' => 40,
                'Ketaatan_Beragama' => 20,
                'Prestasi' => 20,
                'Kedisiplinan' => 30,
                'Kepedulian' => 20,
                'Jarak' => 40,
            ],
            [
                'name' => 'Bagus Fitra Raya',
                'gender' => 'laki-laki',
                'birthplace_and_date' => 'Semarang, 09/03/2018',
                'Umur_Tahun' => 50,
                'Afirmasi_Perpindahan_Orang_Tua' => 20,
                'Potensi_Kecerdasan' => 40,
                'Penghasilan_Orang_Tua_Rupiah' => 50,
                'Kemampuan_Komunikasi' => 50,
                'Ketaatan_Beragama' => 10,
                'Prestasi' => 10,
                'Kedisiplinan' => 40,
                'Kepedulian' => 10,
                'Jarak' => 40,
            ],
            [
                'name' => 'Bintang Pratama',
                'gender' => 'laki-laki',
                'birthplace_and_date' => 'Makassar, 17/10/2013',
                'Umur_Tahun' => 30,
                'Afirmasi_Perpindahan_Orang_Tua' => 50,
                'Potensi_Kecerdasan' => 40,
                'Penghasilan_Orang_Tua_Rupiah' => 50,
                'Kemampuan_Komunikasi' => 30,
                'Ketaatan_Beragama' => 10,
                'Prestasi' => 10,
                'Kedisiplinan' => 50,
                'Kepedulian' => 10,
                'Jarak' => 40,
            ],

            [
                'name' => 'Adi Saputra',
                'gender' => 'laki-laki',
                'birthplace_and_date' => 'Palembang, 30/06/2012',
                'Umur_Tahun' => 10,
                'Afirmasi_Perpindahan_Orang_Tua' => 10,
                'Potensi_Kecerdasan' => 30,
                'Penghasilan_Orang_Tua_Rupiah' => 50,
                'Kemampuan_Komunikasi' => 50,
                'Ketaatan_Beragama' => 50,
                'Prestasi' => 10,
                'Kedisiplinan' => 50,
                'Kepedulian' => 30,
                'Jarak' => 50,
            ],
            [
                'name' => 'Andi Setiawan',
                'gender' => 'laki-laki',
                'birthplace_and_date' => 'Bogor, 11/02/2016',
                'Umur_Tahun' => 10,
                'Afirmasi_Perpindahan_Orang_Tua' => 10,
                'Potensi_Kecerdasan' => 30,
                'Penghasilan_Orang_Tua_Rupiah' => 20,
                'Kemampuan_Komunikasi' => 50,
                'Ketaatan_Beragama' => 50,
                'Prestasi' => 50,
                'Kedisiplinan' => 30,
                'Kepedulian' => 30,
                'Jarak' => 10,
            ],
            [
                'name' => 'Siti Aminah',
                'gender' => 'perempuan',
                'birthplace_and_date' => 'Yogyakarta, 25/08/2017',
                'Umur_Tahun' => 20,
                'Afirmasi_Perpindahan_Orang_Tua' => 20,
                'Potensi_Kecerdasan' => 20,
                'Penghasilan_Orang_Tua_Rupiah' => 20,
                'Kemampuan_Komunikasi' => 50,
                'Ketaatan_Beragama' => 50,
                'Prestasi' => 50,
                'Kedisiplinan' => 40,
                'Kepedulian' => 40,
                'Jarak' => 10,
            ],

            [
                'name' => 'Fitriah Nur Afifah',
                'gender' => 'perempuan',
                'birthplace_and_date' => 'Malang, 08/05/2013',
                'Umur_Tahun' => 40,
                'Afirmasi_Perpindahan_Orang_Tua' => 50,
                'Potensi_Kecerdasan' => 20,
                'Penghasilan_Orang_Tua_Rupiah' => 30,
                'Kemampuan_Komunikasi' => 40,
                'Ketaatan_Beragama' => 50,
                'Prestasi' => 50,
                'Kedisiplinan' => 20,
                'Kepedulian' => 40,
                'Jarak' => 20,
            ],
            [
                'name' => 'Andre Muhammad Taulany',
                'gender' => 'laki-laki',
                'birthplace_and_date' => 'Depok, 19/01/2018',
                'Umur_Tahun' => 40,
                'Afirmasi_Perpindahan_Orang_Tua' => 50,
                'Potensi_Kecerdasan' => 20,
                'Penghasilan_Orang_Tua_Rupiah' => 10,
                'Kemampuan_Komunikasi' => 40,
                'Ketaatan_Beragama' => 30,
                'Prestasi' => 20,
                'Kedisiplinan' => 20,
                'Kepedulian' => 20,
                'Jarak' => 20,
            ],
            [
                'name' => 'Fatimah Ayu Sekar',
                'gender' => 'perempuan',
                'birthplace_and_date' => 'Tangerang, 01/11/2014',
                'Umur_Tahun' => 50,
                'Afirmasi_Perpindahan_Orang_Tua' => 30,
                'Potensi_Kecerdasan' => 30,
                'Penghasilan_Orang_Tua_Rupiah' => 10,
                'Kemampuan_Komunikasi' => 30,
                'Ketaatan_Beragama' => 40,
                'Prestasi' => 10,
                'Kedisiplinan' => 10,
                'Kepedulian' => 30,
                'Jarak' => 10,
            ],

            [
                'name' => 'Diki Setiawan',
                'gender' => 'laki-laki',
                'birthplace_and_date' => 'Padang, 14/07/2015',
                'Umur_Tahun' => 30,
                'Afirmasi_Perpindahan_Orang_Tua' => 40,
                'Potensi_Kecerdasan' => 50,
                'Penghasilan_Orang_Tua_Rupiah' => 20,
                'Kemampuan_Komunikasi' => 20,
                'Ketaatan_Beragama' => 20,
                'Prestasi' => 20,
                'Kedisiplinan' => 10,
                'Kepedulian' => 20,
                'Jarak' => 20,
            ],
            [
                'name' => 'Agus Dwi Wahyudi',
                'gender' => 'laki-laki',
                'birthplace_and_date' => 'Batam, 27/04/2016',
                'Umur_Tahun' => 30,
                'Afirmasi_Perpindahan_Orang_Tua' => 20,
                'Potensi_Kecerdasan' => 50,
                'Penghasilan_Orang_Tua_Rupiah' => 20,
                'Kemampuan_Komunikasi' => 20,
                'Ketaatan_Beragama' => 10,
                'Prestasi' => 10,
                'Kedisiplinan' => 10,
                'Kepedulian' => 10,
                'Jarak' => 10,
            ],
            [
                'name' => 'Indra Firman Saputra',
                'gender' => 'laki-laki',
                'birthplace_and_date' => 'Pekanbaru, 06/12/2017',
                'Umur_Tahun' => 10,
                'Afirmasi_Perpindahan_Orang_Tua' => 20,
                'Potensi_Kecerdasan' => 40,
                'Penghasilan_Orang_Tua_Rupiah' => 30,
                'Kemampuan_Komunikasi' => 10,
                'Ketaatan_Beragama' => 50,
                'Prestasi' => 50,
                'Kedisiplinan' => 50,
                'Kepedulian' => 50,
                'Jarak' => 40,
            ],

            [
                'name' => 'Muhammad Ilham',
                'gender' => 'laki-laki',
                'birthplace_and_date' => 'Bandar Lampung, 18/09/2012',
                'Umur_Tahun' => 10,
                'Afirmasi_Perpindahan_Orang_Tua' => 50,
                'Potensi_Kecerdasan' => 40,
                'Penghasilan_Orang_Tua_Rupiah' => 30,
                'Kemampuan_Komunikasi' => 10,
                'Ketaatan_Beragama' => 40,
                'Prestasi' => 30,
                'Kedisiplinan' => 40,
                'Kepedulian' => 40,
                'Jarak' => 30,
            ],
            [
                'name' => 'Ferdi Virgiawan',
                'gender' => 'laki-laki',
                'birthplace_and_date' => 'Denpasar, 02/03/2013',
                'Umur_Tahun' => 40,
                'Afirmasi_Perpindahan_Orang_Tua' => 20,
                'Potensi_Kecerdasan' => 40,
                'Penghasilan_Orang_Tua_Rupiah' => 10,
                'Kemampuan_Komunikasi' => 10,
                'Ketaatan_Beragama' => 40,
                'Prestasi' => 40,
                'Kedisiplinan' => 40,
                'Kepedulian' => 40,
                'Jarak' => 20,
            ],
            [
                'name' => 'Erfan Hakim',
                'gender' => 'laki-laki',
                'birthplace_and_date' => 'Samarinda, 15/10/2014',
                'Umur_Tahun' => 50,
                'Afirmasi_Perpindahan_Orang_Tua' => 10,
                'Potensi_Kecerdasan' => 20,
                'Penghasilan_Orang_Tua_Rupiah' => 10,
                'Kemampuan_Komunikasi' => 40,
                'Ketaatan_Beragama' => 30,
                'Prestasi' => 30,
                'Kedisiplinan' => 30,
                'Kepedulian' => 50,
                'Jarak' => 20,
            ],

            [
                'name' => 'Kurnia Kencana',
                'gender' => 'perempuan',
                'birthplace_and_date' => 'Tarakan, 28/06/2015',
                'Umur_Tahun' => 40,
                'Afirmasi_Perpindahan_Orang_Tua' => 30,
                'Potensi_Kecerdasan' => 20,
                'Penghasilan_Orang_Tua_Rupiah' => 20,
                'Kemampuan_Komunikasi' => 40,
                'Ketaatan_Beragama' => 20,
                'Prestasi' => 20,
                'Kedisiplinan' => 50,
                'Kepedulian' => 50,
                'Jarak' => 50,
            ],
            [
                'name' => 'Dwi Novita Sari',
                'gender' => 'perempuan',
                'birthplace_and_date' => 'Pontianak, 09/02/2016',
                'Umur_Tahun' => 20,
                'Afirmasi_Perpindahan_Orang_Tua' => 20,
                'Potensi_Kecerdasan' => 10,
                'Penghasilan_Orang_Tua_Rupiah' => 50,
                'Kemampuan_Komunikasi' => 30,
                'Ketaatan_Beragama' => 20,
                'Prestasi' => 20,
                'Kedisiplinan' => 50,
                'Kepedulian' => 10,
                'Jarak' => 10,
            ],
            [
                'name' => 'Dimas Maulana',
                'gender' => 'laki-laki',
                'birthplace_and_date' => 'Pasuran, 19/01/2019',
                'Umur_Tahun' => 30,
                'Afirmasi_Perpindahan_Orang_Tua' => 40,
                'Potensi_Kecerdasan' => 20,
                'Penghasilan_Orang_Tua_Rupiah' => 10,
                'Kemampuan_Komunikasi' => 20,
                'Ketaatan_Beragama' => 30,
                'Prestasi' => 20,
                'Kedisiplinan' => 50,
                'Kepedulian' => 20,
                'Jarak' => 50,
            ],
            [
                'name' => 'Novita Ayu Sekar',
                'gender' => 'perempuan',
                'birthplace_and_date' => 'Banten, 01/11/2014',
                'Umur_Tahun' => 40,
                'Afirmasi_Perpindahan_Orang_Tua' => 40,
                'Potensi_Kecerdasan' => 20,
                'Penghasilan_Orang_Tua_Rupiah' => 30,
                'Kemampuan_Komunikasi' => 40,
                'Ketaatan_Beragama' => 20,
                'Prestasi' => 20,
                'Kedisiplinan' => 10,
                'Kepedulian' => 30,
                'Jarak' => 10,
            ],

            [
                'name' => 'Diki Dwi Putranto',
                'gender' => 'laki-laki',
                'birthplace_and_date' => 'Jember, 14/07/2015',
                'Umur_Tahun' => 20,
                'Afirmasi_Perpindahan_Orang_Tua' => 50,
                'Potensi_Kecerdasan' => 20,
                'Penghasilan_Orang_Tua_Rupiah' => 30,
                'Kemampuan_Komunikasi' => 10,
                'Ketaatan_Beragama' => 10,
                'Prestasi' => 20,
                'Kedisiplinan' => 10,
                'Kepedulian' => 20,
                'Jarak' => 20,
            ],
            [
                'name' => 'Agus Dwi Hermawan',
                'gender' => 'laki-laki',
                'birthplace_and_date' => 'Batam, 27/04/2016',
                'Umur_Tahun' => 40,
                'Afirmasi_Perpindahan_Orang_Tua' => 10,
                'Potensi_Kecerdasan' => 30,
                'Penghasilan_Orang_Tua_Rupiah' => 40,
                'Kemampuan_Komunikasi' => 30,
                'Ketaatan_Beragama' => 10,
                'Prestasi' => 10,
                'Kedisiplinan' => 10,
                'Kepedulian' => 10,
                'Jarak' => 10,
            ],
            [
                'name' => 'Doni Firman Irawan',
                'gender' => 'laki-laki',
                'birthplace_and_date' => 'Pekanbaru, 06/12/2017',
                'Umur_Tahun' => 20,
                'Afirmasi_Perpindahan_Orang_Tua' => 30,
                'Potensi_Kecerdasan' => 30,
                'Penghasilan_Orang_Tua_Rupiah' => 20,
                'Kemampuan_Komunikasi' => 20,
                'Ketaatan_Beragama' => 40,
                'Prestasi' => 40,
                'Kedisiplinan' => 10,
                'Kepedulian' => 10,
                'Jarak' => 20,
            ],

            [
                'name' => 'Muhammad Ilzam Mulhaq',
                'gender' => 'laki-laki',
                'birthplace_and_date' => 'Bandar Lampung, 18/09/2012',
                'Umur_Tahun' => 10,
                'Afirmasi_Perpindahan_Orang_Tua' => 50,
                'Potensi_Kecerdasan' => 50,
                'Penghasilan_Orang_Tua_Rupiah' => 30,
                'Kemampuan_Komunikasi' => 30,
                'Ketaatan_Beragama' => 50,
                'Prestasi' => 10,
                'Kedisiplinan' => 40,
                'Kepedulian' => 40,
                'Jarak' => 10,
            ],
            [
                'name' => 'Ferdi Asmoro',
                'gender' => 'laki-laki',
                'birthplace_and_date' => 'Denpasar, 02/03/2013',
                'Umur_Tahun' => 30,
                'Afirmasi_Perpindahan_Orang_Tua' => 10,
                'Potensi_Kecerdasan' => 40,
                'Penghasilan_Orang_Tua_Rupiah' => 30,
                'Kemampuan_Komunikasi' => 40,
                'Ketaatan_Beragama' => 20,
                'Prestasi' => 20,
                'Kedisiplinan' => 30,
                'Kepedulian' => 40,
                'Jarak' => 10,
            ],
            [
                'name' => 'Irfan Hakim',
                'gender' => 'laki-laki',
                'birthplace_and_date' => 'Samarinda, 15/10/2014',
                'Umur_Tahun' => 50,
                'Afirmasi_Perpindahan_Orang_Tua' => 10,
                'Potensi_Kecerdasan' => 20,
                'Penghasilan_Orang_Tua_Rupiah' => 10,
                'Kemampuan_Komunikasi' => 40,
                'Ketaatan_Beragama' => 30,
                'Prestasi' => 30,
                'Kedisiplinan' => 30,
                'Kepedulian' => 50,
                'Jarak' => 20,
            ],

            [
                'name' => 'Kurnia Putri',
                'gender' => 'perempuan',
                'birthplace_and_date' => 'Tarakan, 28/06/2015',
                'Umur_Tahun' => 40,
                'Afirmasi_Perpindahan_Orang_Tua' => 30,
                'Potensi_Kecerdasan' => 20,
                'Penghasilan_Orang_Tua_Rupiah' => 20,
                'Kemampuan_Komunikasi' => 40,
                'Ketaatan_Beragama' => 20,
                'Prestasi' => 20,
                'Kedisiplinan' => 50,
                'Kepedulian' => 50,
                'Jarak' => 50,
            ],
            [
                'name' => 'Dwi Indah Lestari',
                'gender' => 'perempuan',
                'birthplace_and_date' => 'Pontianak, 09/02/2016',
                'Umur_Tahun' => 20,
                'Afirmasi_Perpindahan_Orang_Tua' => 20,
                'Potensi_Kecerdasan' => 10,
                'Penghasilan_Orang_Tua_Rupiah' => 50,
                'Kemampuan_Komunikasi' => 30,
                'Ketaatan_Beragama' => 20,
                'Prestasi' => 20,
                'Kedisiplinan' => 50,
                'Kepedulian' => 10,
                'Jarak' => 10,
            ]

        ];
        $latestSiswa = student::orderBy('id', 'desc')->first();
        $codeNumber = $latestSiswa ? intval(substr($latestSiswa->code, 1)) : 0;

        $nisnList = [
            '1234567890', '1234567891', '1234567892', '1234567893', '1234567894',
            '1234567895', '1234567896', '1234567897', '1234567898', '1234567899',
            '1234567895', '1234567896', '1234567897', '1234567898', '1234567899',
            '1234567800', '1234567801', '1234567802', '1234567803', '1234567804',
            '1234567805', '1234567806', '1234567807', '1234567808', '1234567809',
            '1234567890', '1234567891', '1234567892', '1234567893', '1234567894'

        ];

        foreach ($siswaList as $siswaData) {
            $codeNumber++;
            $siswaData['code'] = 'A' . $codeNumber;
            $siswaData['NISN'] = $nisnList[$codeNumber - 1];
            student::create($siswaData);
        }
    }
}
